linters:
  enable-all: true
  disable:
    - golint     # The repository of the linter has been archived by the owner. Replaced by revive
    - interfacer # The repository of the linter has been archived by the owner.
    - maligned   # The repository of the linter has been archived by the owner. Replaced by govet 'fieldalignment'.
    - scopelint  # The repository of the linter has been deprecated by the owner. Replaced by exportloopref.

    - lll        # Reports long lines
