linters:
  enable-all: true
  disable:
    - exhaustivestruct # deprecated
    - golint # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - scopelint # deprecated
    - bodyclose # disabled because of go1.18
    - contextcheck # disabled because of go1.18
    - nilerr # disabled because of go1.18
    - noctx # disabled because of go1.18
    - rowserrcheck # disabled because of go1.18
    - sqlclosecheck # disabled because of go1.18
    - structcheck # disabled because of go1.18
    - tparallel # disabled because of go1.18
    - unparam # disabled because of go1.18
    - wastedassign # disabled because of go1.18
    - lll
